### ISSUE TITLE
Plain pages when Javascript is disabled

### ISSUE THREAD

**Issue by StanleyMasinde** [stannlee/online-suggestionbox#1]
**Describe the bug**

**To Reproduce**
1. Go to the home page after login
2. Click on disable javascript you can also unlink the ```app.js```
3. See error

**Comment by Donstesh** [comment]
Awsome app real representation of a true dev with passion to what you do...I love this app

**Comment by StanleyMasinde** [comment]
@donstesh I need you guys to fix the bug that's the point of opening this issue

**Comment by cyrus43** [comment]
One disables JavaScript in a browser environment because of the following considerations:

1.Speed & Bandwidth
2.Usability & Accessibility
3.Platform Support
4.Security

**Comment by cyrus43** [comment]
Am yet to comment, that was my view about disabling JavaScript via internet....Am reviewing the issue

**Comment by StanleyMasinde** [comment]
@cyrus43 I count on you you are the JavaScript guy... na sijasema wengine hamuezi
